/app/test:
  get:
    summary: Test API - Always returns SUCCESS
    tags: [Test]
    responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              type: object
              properties:
                isSucess:
                  type: boolean
                  example: true
                code:
                  type: int
                  example: 1000
