/app/users/api/token:
  get:
    summary: 인증번호 6자리 SMS 전송 API
    tags: [User]
    requestBody:
      description: 인증번호를 전송할 전화번호
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              phoneNumber:
                type: string
                example: 01053971011
    responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              type: object
              properties:
                isSucess:
                  type: boolean
                  example: true
                code:
                  type: int
                  example: 1000
                result:
                  type: object
                  properties:
                    token:
                      type: string
                      example: 712031
